name: Test templates

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

jobs:

  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run ARM TTK
      uses: ./action-armttk
